Algoritmo "Exercicico 1"

Var
 idade: inteiro
 nome: caracter



Inicio
      escreval("digite o seu nome")
      leia(nome)
      escreval("digite a sua idade para saber se você pode tirar a CNH")
      leia(idade)
      se idade >= 18 entao
      escreval("senhor(a) ", nome," voce pode tirar a CNH")
      senao
      escreval("senhor(a)", nome," voce nao pode tirar a CNH")
      fimse


Fimalgoritmo