Algoritmo "Exercicico 6"

Var
v1,v2,v3,maior: real



Inicio
      escreval("digite o primeiro valor")
      leia(v1)
      maior<-v1
      escreval("digite o segundo valor")
      leia(v2)
      se(v2 > maior)entao
      maior<-v2
      fimse
      escreval("digite o terceiro valor")
      leia(v3)
      se(v3 > maior)entao
      maior<-v3
      fimse
      escreval("o maior numero e:",maior)
Fimalgoritmo