Algoritmo "Exercicico 4"

Var
 valor1,valor2:real



Inicio
      escreval("digite um numero")
      leia(valor1)
      escreval("digite outro numero")
      leia(valor2)
      se valor1 > valor2 entao
      escreval(valor1," e maior que ", valor2)
         senao
         se valor2 > valor1 entao
         escreval(valor2," e maior que ", valor1)
             senao
             escreval(valor1," e igual a ", valor2)
         fimse
      fimse


Fimalgoritmo